import os.path

VERSION = '2.8.4'
MAIN_VERSION = '2'
SUB_VERSION = '-rev 1'
CODENAME = '"Twenty One Pilots"'
VER = VERSION + SUB_VERSION
BDATE = 'June 27, 2016 @ 12:48 AM EDT'
MAINVER = VERSION + SUB_VERSION + CODENAME
BUILD_USERNAME = "Wyndrik"
AUDIO_CACHE_PATH = os.path.join(os.getcwd(), 'audio_cache')
DISCORD_MSG_CHAR_LIMIT = 2000