 
psat_memes = [
    "https://this.dragonfire.me/website/sucks/fddd6e.png",
    "https://this.dragonfire.me/website/sucks/43f785.png",
    "https://this.dragonfire.me/website/sucks/02c8b6.png",
    "https://this.dragonfire.me/website/sucks/e2a7dc.png",
    "https://pbs.twimg.com/media/DL-BOiOWAAAllWB.jpg:large",
    "https://this.dragonfire.me/website/sucks/0f2f92.png",
    "https://this.dragonfire.me/website/sucks/abe6b5.png",
    "https://pbs.twimg.com/media/DL83LiwXUAEbJfJ.jpg:large",
    "https://this.dragonfire.me/website/sucks/303706.png",
    "https://this.dragonfire.me/website/sucks/01f5c8.png",
    "https://this.dragonfire.me/website/sucks/c717e3.png",
    "https://this.dragonfire.me/website/sucks/4c5379.png",
    "https://this.dragonfire.me/website/sucks/2df267.png",
    "https://this.dragonfire.me/website/sucks/99764b.png",
    "https://this.dragonfire.me/website/sucks/37137c.png",
    "https://this.dragonfire.me/website/sucks/da2a31.png",
    "https://this.dragonfire.me/website/sucks/03db1f.png",
    "https://this.dragonfire.me/website/sucks/008943.png",
    "https://pbs.twimg.com/media/DL6BXltV4AEBulp.jpg:large", # revolutionary
    "https://this.dragonfire.me/website/sucks/7ea7c2.png",
    "https://this.dragonfire.me/website/sucks/062647.png",
    "https://pbs.twimg.com/media/DL57so5UEAINZ1_.jpg:large",
    "https://this.dragonfire.me/website/sucks/11595c.png",
    "https://this.dragonfire.me/website/sucks/67ad23.png",
    "https://this.dragonfire.me/website/sucks/ae8863.png",
    "https://this.dragonfire.me/website/sucks/292ec9.png",
    "https://this.dragonfire.me/website/sucks/15e09c.png",
    "https://this.dragonfire.me/website/sucks/e9e690.png",
    "https://this.dragonfire.me/website/sucks/97ac3d.png",
    "https://this.dragonfire.me/website/sucks/99c7de.png"
]

# Response for the 8ball command
magic_conch_shell = [
    "probably certain.",
    "let's go with it's most likely true",
    "without a doubt!",
    "definitely fam",
    "it's reliable enough.",
    "well, it looks like it.",
    "mhm, most likely",
    "outlook looks good on this one.",
    "yes.",
    "every damn sign points to yes",
    "reply hazy, retry.",
    "ask later.",
    "better not tell you now",
    "can't predict at the moment",
    "think hard, then ask again.",
    "yeah, don't count on it.",
    "my reply is a definite no.",
    "my sources say no.",
    "outlook doesn't look nice",
    "mmm doubtful.",
    "maybe not..."
]

# Insults for the insult command
insults = [
    "is a fucking pedophile",
    "is so insecure about his penis size because it is smaller than a babies",
    "is just a fucking sterotypical 12 year old saying shit like \"I fucked your mom\" and other shit",
    "is a fucking disguisting, disgraceful, ignorant, pathetic, and discriminative weeaboo!",
    "is a child molester",
    "has a kink with 80 year old men",
    "is the type of person who loves to fap to little girls",
    "has no other purpose in life other than to be retarded and waste people's time",
    "needs to kill itself",
    "is the definition of faggot",
    "has a gamertag, and it is I_Like_To_Rape_Children",
    "loves to fap to discord bots",
    "wants the d",
    "has no life",
    "is a furry",
    "is a furfag",
    "is a worthless piece of shit",
    "is an 80 year old man",
    "lost his virginity to his grandpa",
    "supports abortion",
    "is a cuntrag",
    "is on the sex offender list",
    "is a fucking shithead",
    "is a scotsman",
    "is a fucking edgelord",
    "needs to fucking die",
    "is a godfucking-shitheaded-pooeating-foureyed-bigheaded-pedofilic-godforesaken-pissdrinking-assfucking-homofilic-beerbellied-mophaired-cronical-heroinaddicted-tetanussuffering-monkeyassed-cocksucking-hepatitisinfected-gangreneinfested-pimplefaced-bugeyed-gasolineinhaling-cokewhore cunt!",
    "is a cheese eating surrender monkey",
    "is a fucking mong",
    "has a high probability of being inbred",
    "eats ass with a condom over their mouth to avoid STD's",
    "buys their daily supplies from poundworld",
    "thinks communism should be implemented into all countries around the world",
    "sits down and drinks tea with a stuffed my little pony toy that they fuck every night",
    "buys their daily supplies from dollar tree",
    "has a dried up pussy"
]


"""
can you also add compliments
so i can feel
that someone loves me
- Asia, 2017
"""
compliments = [
    "...i like your hair",
    "you're really nice",
    "....yeah uhm, you're amazing",
    "you're a wonderful person",
    "i like you.....",
    "your hair doesn't look like a weave, it's actually real."
    ]

# Drunk lines for the actdrunk command
drunkaf = [
    "UDNDUNDUNDUNDUDNUDNDUNDUNDUNDUNDUNDUDNUDNDUNDUNDUNDUNDUNDUNDUNDNUDNDUN",
    "AMERICAN IDIOTS YAAAS",
    "HEH HEH HEH HEH IM SO FUKED UP LOL",
    "lol Ill fuk u up n@4f3 fucjing fite me4",
    "fite me u lil fuck",
    "i have somethin to tell you: fedc",
    "weeeeeeew",
    "\*falls*",
    "lol wana fuk some suc tonight #5SdE2@",
    "WHATS WROMG WWITHY MY LIFJUE JKNAKLFCNASEKLF W KJLNSDFKL XNFKLJB SRL"
]

# Image urls for the honk command
honkhonkfgt = [
    "https://i.imgur.com/c53XQCI.gif",
    "https://i.imgur.com/ObWBP14.png",
    "https://i.imgur.com/RZP2tB4.jpg",
    "https://i.imgur.com/oxQ083P.gif",
    "https://i.imgur.com/byBB7ln.jpg",
    "https://i.imgur.com/NvUiLGG.gif",
    "https://i.imgur.com/QDyvO4x.jpg",
    "https://i.imgur.com/HtrRYSS.png",
    "https://i.imgur.com/bvrFQnX.jpg"
]

#image urls for the furry bullshit, discord's cdn probably killed those links
#as of September 15, 2017 at 10:16 PM EDT, it is not dead what the fuck? https://my.mixtape.moe/maelpo.png
tweetsthatareokhand = [
    "http://i.imgur.com/lkMJ1O9.png",
    "http://i.imgur.com/rbGmZqV.png",
    "http://i.imgur.com/hYzNxVR.png",
    "http://i.imgur.com/JuVsIMg.png",
    "http://i.imgur.com/2NYwUcj.png",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222732260442113/train_of_horses.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222728338636802/they_wshiper.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222725977243650/thats_my_boyfriend.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222723175579650/pinned.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222720667385858/list.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222717743824907/idea_of_music.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222715147550721/goals.PNG",
#    "here's a message from the coder of this: I FUCKING RAN OUT NEEDS MORE CHEESE",
# not anymore, its like what 21 links
   "​https://cdn.discordapp.com/attachments/173886531080159234/176425292426903553/f20e683862a17ef49633eed742fc2b22eb17220eef5a1d607cda2e7a7758720b_1.jpg",
    "http://i.imgur.com/m71nJAg.png",
    "http://i.imgur.com/m5fx7U9.png",
    "https://cdn.discordapp.com/attachments/173887966031118336/177518766781890562/your-resistance-only-makes-my-penis-harder.jpg",
    "http://i.imgur.com/21bV05w.png",
    "http://i.imgur.com/7Y94F7L.png",
    "H-hewwo? OwO are you dewe?"
]

#people
#santropez
santropez = [
    ":~)",
    ":~)",
    ":-)",
    ":^)",
    ":)",
    ":'~)",
    "**:)**",
    "**(:**",
    ":racehorse:",
    ":horse:",
    "(:",
    "pppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhtttttttttttttttttttt",
    "pppppppppppppppppppppppppppppppppppppppppppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhtttttttttttttttttttt",
    "I SPIT ON YOU.",
    "Nine nine nine",
    ":drum: :racehorse:",
    ":french_bread:",
    ":duck:",
    "spt",
    "spt2",
    "***blacklist commodore***",
    "***women\nbe\nshopping***",
    "bukbot's funny body movement makes me have anything",
    ":thinking:",
    "i love building pyramids",
    "dævid bjøwie",
    "Davidt Gilmourt",
    "GILMOUR & PINK FLOYD",
    "THE WATERS FUNNY MOVEMENT MAKES ME HAVE ANYTHING",
    "YOU CHOICE",
    "THE WATERS",
    "SDFNJKSNJEQWERQKEQQ2LQNRL23OHR23HRNERADFSBBWDJLQBLQWDQDNWDFJEWPABDSKJBCF23HNQROU32U0JNLASBFLDBDLNBAJLSLFEQWR K23RBFDNASNJJSJDDFHDDISDFSDFI999999999999999999999999999999999",
    "ƒ˙˙ƒ∂ßƒ∑ø¥ƒ£¢º£•¥˙ˆß¬˜¬∂ßff",
    "PLELEDSE STOP",
    "ssssssssssssssssssssspppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppptttttttttttttttttttttttttt"
]

#kurt
zekurt = [
    "viva la poutine",
    "viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine",
    "you fucking wot mate",
    "*torenaments*",
    "i was told canada was cold",
    "viva la tim hortons",
    "https://cdn.discordapp.com/attachments/352132036552556554/398373970673532928/8V013MC.png",
    "fuck you guys and your snow day",
    "haha xd",
    "viva la milk bags",
    "fuckboi indeed",
    "damn",
    "ah shit",
    #these following 3 are together
    "hah get fucked my 2018 will last longer than yours"
    "\nalso I'd like to say that I fulfilled my wish"
    "\nto nut exactly at 12",
    "shit",
    "thought we killed galahad",
    "we fucked",
    "yeah i hate that guy",
    "yall are allowed into the club",
    "if Kash the Pure does then I'm sure everyone does",
    "lmao all good",
    "rip kash :broken_heart:",
    "fuck cumwhore",
    ":eyes: confirmed",
    "remember boys and girls god isn't real",
    "death is nothingness for eternity",
    "connor is a disappointment",
    "connor ***DROPS DICK ON TABLE*** I AM AN EXECUTIVE OBEY",
    "connor: hey guys just wanted to remind everyone that i am technically an executive",
    "everyone is death",
    "i am out i can't join",
    "Lil dick",
    "fuck you",
    "true",
    "https://i.redd.it/mf4rnsbonx501.jpg"
    "@ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut",
    "i typed tree into cmd",
    "that's not gay because some of those men probably kissed women",
    "***can fat girls get away with murder if they accidentally crush their man while on top***  :thinking:",
    "P U P P E T  O W N E R",
    "cumwhore do you ever just open your mouth and then realize no one fucking cares",
    "MEGA BRITANNIA",
    "man i just fucking realized the Scandinavian flags are just crosses",
    "CASCADIA SHALL BE FREE",
    "VIVA LA CASCADIA",
    "get fucked",
    "discount austria",
    "not terrible",
    ";;;;;;;;;;;;;;;;;;;;;;;;;",
    "i can't believe the jar jar binks theory was true",
    ":eyes:",
    "***no nasty drama allowed on this christian server***",
    ":thinking:",
    "huh",
    "get reported",
    "god infamas pisses me off",
    "I'd probably get fucked",
    "i am so goddamn disappointed",
    "nut",
    "mecha trump",
    "that's my boy",
    "good job",
    "zekurt for prime minister",
    "oprah as president: *pointing to the rich* \"you get a tax cut, you get a tax cut, everyone gets a tax cut!\"",
    "oprah as president: pointing to the poor \"you get a petrol tax increase, you get a petrol tax increase, everyone gets a petrol tax increase!\"",
    "i like canada dry",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n\n\nif you look at it long enough\nthey don't really look like a's anymore",
    "one sec going to build the wall",
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHh",
    "disorienting",
    "legalize crystal gay weed",
    "also how does it feel that trump is going to cuck legalized pot",
    "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "That's me",
    "Gay",
    "robin es gay",
    "actually it's a fact that traps are gay it stated in the bible that if one think of thou trap as sexy than thou art of homosexuality",
    "rip",
    "would you look like this",
    "this is ryan as your caretaker https://cdn.discordapp.com/attachments/400012212791541762/401545625134694400/PROD-Egg.png",
    "actually you don't have legs so you require someone to carry you",
    "you go \'oof\' when you take damage",
    "you are square shaped",
    "i'm sorry to be the one to tell you"
    "\nthat you exactly look like a roblox character",
    "i thought roblox was just an england simulator",
    "what a life",
    "shrewd kim jong un",
    "true that",
    ":thinking",
    "KHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN",
    "maple syrup is basically enough to feed me and keep me hydrated",
    "true, previous zekurt",
    "أريد أن أكل سلحفاة البحر العملاقة",
    "كيف سرق غرينش عيد الميلاد",
    "factually incorrect",
    "canadia will into conquer north america",
    "^",
    "bird",
    "fish",
    "fish",
    "fish",
    "bird",
    "do I ever say things",
    "eat fish",
    "it be true",
    "kek not even cold",
    "battlerite royale",
    "ye but gotta be airtight",
    "remove",
    "infamas is a cuck",
    "my joke",
    "connor redemption arc",
    "get me hard",
    "bully me",
    "In middle school I'd go to the mini gym and sleep in this dark and secluded comfy place sometimes",
    "Damn this hot weather",
    "Chapped lips is not fun",
    "ban functionality",
    "kwargs chad",
    "Georgia man be weird",
    "kek likely",
    "Keep up the returns and maybe you'll have a seat at the big boy table",
    "I say yikes but nothing else",
    "Let's get this racism",
    "Can conservative gamers please rise up",
    "goodnight lads",
    "worth staying up until 6am",
    "warm",
    "almost ugly as me",
    "agree",
    "I am too strong",
    "no",
    "i'll pee on it",
    "didn't see",
    "fucked",
    "Didn't see it",
    "Wasn't looking",
    "You watched all of mine",
    "I established dominance by peeing whole watching",
    "shut up",
    "better than sea of thieves",
    "it's time to stop",
    "lots of nervous laughter",
    "same",
    "true",
    "kek",
    "sode: I don't hate gay people... I'm not racist",
    "NEXT UP AN EXCITING ANNOUNCEMNET FROM FORTNITE",
    "it was worth a try",
    "the outer worlds",
    "fallout new vegas in space",
    "big sigh",
    "NINJA <:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064><:REEEEE~1:433752311085400064>",
    "<:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048><:cringe:455772365679362048>",
    "you are orb"
]

#penis
nero = [
    ":(",
    "ME FIRST :(",
    "ROOOOD ROBINNNN YUHHHHH",
    ":thinking:",
    "where mine",
    ".nero",
    "WHAT'S GUCCI MY G?",
    "whats gucci my g",
    ".jake",
    "jake is a dog fucker",
    "jake how's the dog penis",
    "HAHAHAAAAAA",
    "No",
    "Oh no",
    "It just turned into a kitten...",
    "UHHH",
    "Amazing",
    "SWOL",
    "I WASNT EXPECTINF THAT",
    "BULLLLLLLAHIET",
    ">:I",
    "heil",
    "S H I T",
    "AHHHH",
    ">:O",
    "ah",
    "i mean",
    "Tru?",
    "<@234005741608894464> find $6,000 please",
    "jake goes to a private school",
    "he has money to fly over here",
    "isnt jake rich",
    "Headass?"
    "\nDo u mean"
    "\nDeadass :thinking:",
    ":rofl: Tesco",
    "#go to sleep you egg",
    "I could tell you da wey",
    "omfg really!!!????",
    "Vps, scusa mi",
    "so u can buy robin a computer but cant buy me a pizza :disappointed_relieved:",
    "Tide pod?",
    "Tide pod racing",
    "tide pod picture",
    "YuH",
    "wheres my command? thinking",
    "Gay",
    ">:/",
    "Spit!",
    "Spit on heim!",
    "YOOOOOO THE BEST SONG BY PF???",
    "im proud",
    "The most edible pokemon is a tide pod",
    "kekd",
    "haha get fucked",
    ":^)",
    "eat my ass",
    "robin hates me", #we'll see about that
    "waste it",
    "Hm",
    "dumbies",
    "Im alive my phone died",
    "Ideas",
    "Pussy pussy pussy marijuana I wanna smoke weed everyday that I'm gonna eat that pussy period wanna",
    "Volevo un gatto nero"
]

#faggot
seth = [
    "h",
    "FUCK",
    "@Nerris this is god looking down at you while you commit your sins https://seth.doesnt-have-a.life/nvvfyjl.png",
    "me",
    "smh",
    "do you have an e-cig charger?",
    "si",
    "nvm",
    "rpbom\ncan i put a bomb threat on a texas instrument calc\nthey wont know its me",
    "bih google exists",
    "if i were the lead dev marco and commodore's expulsion will be my first action",
    "is fix",
    "i dont get it",
    "since when do we allow kykes on the forums",
    "what hoe",
    "https://seth.doesnt-have-a.life/nbjjl2y.png SELF FRIENDSHIP RIGHT VIOLATIONS",
    "Knigge we got to go move a dick I woke up",
    "Robert we got to go move a dick I woke up",
    "Correction Mark Shamrock Shamrock Shamrock Shamrock Shamrock Shamrock Shamrock Shamrock Shamrock Shamrock",
    "Andre please don't don't fucking mean me",
    "Never never never never never never never never never never never never never never NIBNIBBA is what I'm trying to fucking say what he comes out as nearby",
    "And I DBA and I BBANIBBA backspace delete all of this text fucking hell there's no commands to get rid of fucking shit in this fucking text box thing fucking hell you fucking their Bob telling you right now never I will fuck you up",
    "https://seth.doesnt-have-a.life/848aora.png",
    "\"woa seth chill the fuck out hoe]\"\n\"FUCKING JEWISH NIGGER SHUT THE FUCK UP CUNT FUCK GO RECIEVE ANAL FROM A FUCKING DRAGON WITH A BIG COCK YOU CLOSET FURRY LOOKING ASS BITCH\"",
    "fucking",
    "fuck iphones",
    "jake is gonna make a furred humanoid\nif he doesnt stop fucking dogs\nHuman spines don’t support bipedal movement which may be an explanation on why babies are such idiots and can’t walk",
    "lets find hood niggas in saginaw",
    "ok nigga",
    "bitch i",
    "fuck that",
    "no you fucking goober",
    "fuck it",
    "@big kfc bucket supreme wake the fuck up",
    "I said \"I wanna fucking die\" in the hallway and the spanish teacher/pe teacher floyd thought I said \"You're all gonna die\" so he told the principal mr. ballfuck on me\nso i fought that old fucker for like 10 mins and now I have ISS until wednesday",
    "o",
    "U AMD FUCK",
    "kms",
    ".play intent to kill",
    "ok fine fuck a piece of paper and get a paper cut on ur dick\nand get a papery std",
	"idk",
    "xd", 
    "i just finished my homework",
    "COME BACK",
    "w",
    "y u do this",
    "help its quiet",
    "plsplspls",
    "I'm alone and it's getting dark",
    "I'm homr",
    "call pls",
    "no leave",
    "actually warm",
    "mack",
    "i need to go run",
    "fat yes",
    "i turned it pogf]\\",
    "i dont have the cc",
    "u always sleep",
    "early out xd",
    "u g tos chool",
    "kjhgfds",
    "I'm gonna bitch at the nigger across the street for blasting Christian nigger music at the mall cost because I don't want to get drunk and act like you",
    "https://en.wikipedia.org/wiki/Christian_communism",
    "\"weather authority\" sounds like some sort of communism",
    "no u",
    ":nigga:",
    "hi",
    "valid",
    "ya but",
    "still gay",
    "only female furries are permit",
    "i ass dialed u",
    "did u silent ur shit",
    "thats hot",
    "hjkuytrew",
    "xd'",
    "this nigga is having problems running my bot on mac\nand im like\n\"i dont have macs im sorry\"",
    "https://cdn.discordapp.com/attachments/189814231741235203/518864272973889547/9f4a3ad84d2e63fd8b14f20edf345b3d.png",
    "me too",
    "👢",
    "AGRE",
    "<:notokhand:358814332861284364>",
    "no monies for you",
    "now where u gonna find money"
]

#cant hear him
ryan = [
    "sand noises",
    "more sand noises"
]

#weeb
troy = [
    "I'm not too narcissistic to remember my year old quotes",
    "Gaaaaa",
    "Wait",
    "You have large gay",
    "\"used to be a large dragon\"",
    "<:feelsanimeman:508054884457906176>",
    "Gonna have furries",
    "100%",
    "Matt",
    "<:GWqlabsKek:393085130219978752>",
    "O h",
    "Is ghey",
    "Oof",
    "Git",
    "Gud",
    "Give me your battery you damn LG user",
    "Ne🅱er heard of",
    "Lit",
    "Remember when motorola\nMeant something",
    "Like this server",
    "Colour",
    "Troy",
    "Gay",
    "That works",
    "Ya cleeron usin lookin",
    "Fake and gay",
    "E w",
    "White boi",
    "Wait no the end",
    "Fuck #0001",
    "You are now in debt",
    "Ignore that",
    "<:GWqlabsArmLeft:398950980537942026>\n<:GWqlabsHyperRage:393085095285882881>\n<:GWqlabsArmRight:398950990813855745>",
    "<:GWqlabsOutage:398950811310489610>",
    "Who this",
    "Again",
    "?",
    "Niceu",
    "Myrrh is my sister",
    "W u t",
    "Don't tell me you deleted them",
    "I cannot be anymore specific",
    "I wouldn't be too surprised",
    "He's a lotta things",
    "Arl showed me the ways of a lolicon",
    "Cater for us, matt",
    "Matt you gotta use miyano emotes",
    "Yhes",
    "Dang",
    "*these emotes must be perfect"
]

#mick
speed = [
    "no anime",
    "brooklyn supreme",
    "hi seth",
    "Rhyfomos",
    "remove robin",
    "i love being a mom but it's tough when my kids come home filthy from radical islamic terrorism",
    ":^)",
    "ah yes",
    "square emo european",
    "wholesome ops",
    "<:okretard:517885620048363523>",
    "Bored? Eat your cum",
    "remove bronx",
    "seth is still sucking his mic"
]

#smh
soopor = [
    "banime",
    "gay",
    "haha yes",
    "speediv mexico",
    "speed = small peepee",
    "lion company",
    "premium mints ex",
    "fortnite gamer",
    "gamer boys",
    "gamer girls",
    "spood 4",
    "remix",
    "lightus",
    "remove furry",
    "hi jake",
    "arsex",
    "thank",
    "fortnite is for gays",
    "lion co",
    "comer la taco",
    "robin mexico",
    "are we the biggest threat to you lately?",
    "default dance supreme",
    "va is south not north you gay",
    "t gay",
    "m"
]

#remove brooklyn
rhyfomos = [
    "remove brooklyn",
    "tea sis",
    "add rhymix or we get bombed by obama",
    ":^)",
    "this is inaccurate",
    "This is so sad",
    "this is a s am",
    "its christmas",
    "remove wecklerie",
    "speaking of burrito, i want a burrito now",
    "thats neato burrito",
    "...",
    "lets make a total freedom rewind",
    "asian superior race",
    "nice one ron",
    "you are stupid",
    "this is why the masculine gender is superior",
    "same",
    "Poxkaks chat",
    "<:thenk:496056094066606090>",
    "let me.educate",
    "no",
    "idk how to spanish",
    "Los bitches",
    "speediv is la bitch",
    "I pissed my spanish teacher one by talking in spanish in a western accent",
    "si",
    "I bet speediv speaks spanisb in the most american way",
    "Fuck you",
    "Robin that's so gay",
    "Robinson",
    "Bomb"
]

#remove emo european
square = [
    "oh",
    "oh",
    "okay",
    "sure",
    "haha yes",
    ":ok_hand:",
    "you're about to lose your discord admin rank",
    "hmm",
    "kek",
    "lmao",
    "sure bud",
    "fuck off",
    "remove speed",
    "slowdiv",
    "remove jake",
    "remove robin",
    "hmmm",
    ":thinking:",
    "let's rule34 that",
    "there's a guy fucking a chair",
    "there's a guy fucking a table",
    "i am not an emo european",
    "i am a square",
    "i am not a circle",
    "thanks",
    "hey",
    "oi",
    "meme stolen",
    "who wants some nsfw memes",
    "i love the internet",
    "i hate the internet",
    "<@315849653763702784>"
]

#transformas12345
chaotix = [
    "wtf gay",
    "SOURCE HIT DETECTION REEEEEEEEEEEEEEEEEEEEEE",
    "lol bye",
    "finna default dance on your grave",
    "shut the up hell fuck",
    "Sans Undertale",
    "family guy funny moments",
    "remove post",
    "generic quote",
    "just don't get hit 4Head",
    "Bruh Sound Effect #2",
    "CUtlRBTree overflow!",
    "Too many shadowed lights! ( 9 > 8 )",
    "go commit gnome self",
    "WAAAAAAAAAAAALMAAAAAAAAAAAAAAAART",
    "Fortnite Funny Fails and WTF Moments! #401",
    "hit or miss, i guess she took the kids huh",
    "le chaotix has arrived",
    "really makes you :think:",
    "lemme smash",
    "** **",
    "free vbucks giveaway",
    "politics LUL",
    "go commit yeet self off cliff",
    "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
    "ready to instantly die",
    "\*confused screaming*",
    "xd",
    "**Upload Failed** Click here to retry the upload",
]
