
psat_memes = [
    "https://this.dragonfire.me/website/sucks/fddd6e.png",
    "https://this.dragonfire.me/website/sucks/43f785.png",
    "https://this.dragonfire.me/website/sucks/02c8b6.png",
    "https://this.dragonfire.me/website/sucks/e2a7dc.png",
    "https://pbs.twimg.com/media/DL-BOiOWAAAllWB.jpg:large",
    "https://this.dragonfire.me/website/sucks/0f2f92.png",
    "https://this.dragonfire.me/website/sucks/abe6b5.png",
    "https://pbs.twimg.com/media/DL83LiwXUAEbJfJ.jpg:large",
    "https://this.dragonfire.me/website/sucks/303706.png",
    "https://this.dragonfire.me/website/sucks/01f5c8.png",
    "https://this.dragonfire.me/website/sucks/c717e3.png",
    "https://this.dragonfire.me/website/sucks/4c5379.png",
    "https://this.dragonfire.me/website/sucks/2df267.png",
    "https://this.dragonfire.me/website/sucks/99764b.png",
    "https://this.dragonfire.me/website/sucks/37137c.png",
    "https://this.dragonfire.me/website/sucks/da2a31.png",
    "https://this.dragonfire.me/website/sucks/03db1f.png",
    "https://this.dragonfire.me/website/sucks/008943.png",
    "https://pbs.twimg.com/media/DL6BXltV4AEBulp.jpg:large", # revolutionary
    "https://this.dragonfire.me/website/sucks/7ea7c2.png",
    "https://this.dragonfire.me/website/sucks/062647.png",
    "https://pbs.twimg.com/media/DL57so5UEAINZ1_.jpg:large",
    "https://this.dragonfire.me/website/sucks/11595c.png",
    "https://this.dragonfire.me/website/sucks/67ad23.png",
    "https://this.dragonfire.me/website/sucks/ae8863.png",
    "https://this.dragonfire.me/website/sucks/292ec9.png",
    "https://this.dragonfire.me/website/sucks/15e09c.png",
    "https://this.dragonfire.me/website/sucks/e9e690.png",
    "https://this.dragonfire.me/website/sucks/97ac3d.png",
    "https://this.dragonfire.me/website/sucks/99c7de.png"
]

# Response for the 8ball command
magic_conch_shell = [
    "probably certain.",
    "ehh, let's say it's true.",
    "without a doubt!",
    "definitely",
    "you can rely on it.",
    "well, it looks like it.",
    "mhm, most likely",
    "outlook looks good on this one.",
    "yes.",
    "every damn sign points to yes",
    "reply hazy, retry.",
    "ask later.",
    "better not tell you now",
    "can't predict at the moment",
    "think hard, then ask again.",
    "yeah, don't count on it.",
    "my reply is a definite no.",
    "my sources say no.",
    "outlook doesn't look nice",
    "mmm doubtful."
]

# Insults for the insult command
insults = [
    "is a fucking pedophile",
    "is a nigger",
    "is so insecure about his penis size because it is smaller than a babies",
    "is just a fucking sterotypical 12 year old saying shit like \"I fucked your mom\" and other shit",
    "is a fucking disguisting, disgraceful, ignorant, pathetic, and discriminative weeaboo!",
    "is a child molester",
    "has a kink with 80 year old men",
    "is the type of person who loves to fap to little girls",
    "has no other purpose in life other than to be retarded and waste people's time",
    "needs to kill itself",
    "is the definition of faggot",
    "has a gamertag, and it is I_Like_To_Rape_Children",
    "loves to fap to discord bots",
    "wants the d",
    "has no life",
    "is a furry",
    "is a furfag",
    "is a worthless piece of shit",
    "is an 80 year old man",
    "lost his virginity to his grandpa",
    "supports abortion",
    "is a cuntrag",
    "is on the sex offender list",
    "is a fucking shithead",
    "is a scotsman",
    "is a fucking edgelord",
    "needs to fucking die",
    "is a godfucking-shitheaded-pooeating-foureyed-bigheaded-pedofilic-godforesaken-pissdrinking-assfucking-homofilic-beerbellied-mophaired-cronical-heroinaddicted-tetanussuffering-monkeyassed-cocksucking-hepatitisinfected-gangreneinfested-pimplefaced-bugeyed-gasolineinhaling-cokewhore cunt!",
    "is a cheese eating surrender monkey",
    "is a fucking mong",
    "has a high probability of being inbred",
    "eats ass with a condom over their mouth to avoid STD's",
    "buys their daily supplies from poundworld",
    "thinks communism should be implemented into all countries around the world",
    "sits down and drinks tea with a stuffed my little pony toy that they fuck every night",
    "buys their daily supplies from dollar tree",
    "has a dried up pussy"
]


"""
can you also add compliments
so i can feel
that someone loves me
- Asia, 2017
"""
compliments = [
    "...i like your hair",
    "you're really nice",
    "....yeah uhm, you're amazing",
    "you're a wonderful person",
    "i like you.....",
    "your hair doesn't look like a weave, it's actually real."
    ]

# Drunk lines for the actdrunk command
drunkaf = [
    "UDNDUNDUNDUNDUDNUDNDUNDUNDUNDUNDUNDUDNUDNDUNDUNDUNDUNDUNDUNDUNDNUDNDUN",
    "AMERICAN IDIOTS YAAAS",
    "HEH HEH HEH HEH IM SO FUKED UP LOL",
    "lol Ill fuk u up n@4f3 fucjing fite me4",
    "fite me u lil fuck",
    "i have somethin to tell you: fedc",
    "weeeeeeew",
    "\*falls*",
    "lol wana fuk some suc tonight #5SdE2@",
    "WHATS WROMG WWITHY MY LIFJUE JKNAKLFCNASEKLF W KJLNSDFKL XNFKLJB SRL"
]

# Image urls for the honk command
honkhonkfgt = [
    "https://i.imgur.com/c53XQCI.gif",
    "https://i.imgur.com/ObWBP14.png",
    "https://i.imgur.com/RZP2tB4.jpg",
    "https://i.imgur.com/oxQ083P.gif",
    "https://i.imgur.com/byBB7ln.jpg",
    "https://i.imgur.com/NvUiLGG.gif",
    "https://i.imgur.com/QDyvO4x.jpg",
    "https://i.imgur.com/HtrRYSS.png",
    "https://i.imgur.com/bvrFQnX.jpg"
]

#image urls for the furry bullshit, discord's cdn probably killed those links
#as of September 15, 2017 at 10:16 PM EDT, it is not dead what the fuck? https://my.mixtape.moe/maelpo.png
tweetsthatareokhand = [
    "http://i.imgur.com/lkMJ1O9.png",
    "http://i.imgur.com/rbGmZqV.png",
    "http://i.imgur.com/hYzNxVR.png",
    "http://i.imgur.com/JuVsIMg.png",
    "http://i.imgur.com/2NYwUcj.png",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222732260442113/train_of_horses.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222728338636802/they_wshiper.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222725977243650/thats_my_boyfriend.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222723175579650/pinned.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222720667385858/list.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222717743824907/idea_of_music.PNG",
    "https://cdn.discordapp.com/attachments/173887966031118336/177222715147550721/goals.PNG",
#    "here's a message from the coder of this: I FUCKING RAN OUT NEEDS MORE CHEESE",
# not anymore, its like what 21 links
   "​https://cdn.discordapp.com/attachments/173886531080159234/176425292426903553/f20e683862a17ef49633eed742fc2b22eb17220eef5a1d607cda2e7a7758720b_1.jpg",
    "http://i.imgur.com/m71nJAg.png",
    "http://i.imgur.com/m5fx7U9.png",
    "https://cdn.discordapp.com/attachments/173887966031118336/177518766781890562/your-resistance-only-makes-my-penis-harder.jpg",
    "http://i.imgur.com/21bV05w.png",
    "http://i.imgur.com/7Y94F7L.png",
    "H-hewwo? OwO are you dewe?"
]

#people
#santropez
santropez = [
    ":~)",
    ":~)",
    ":-)",
    ":^)",
    ":)",
    ":'~)",
    "**:)**",
    "**(:**",
    ":racehorse:",
    ":horse:",
    "(:",
    "pppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhtttttttttttttttttttt",
    "pppppppppppppppppppppppppppppppppppppppppppppppppppppppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhtttttttttttttttttttt",
    "I SPIT ON YOU.",
    "Nine nine nine",
    ":drum: :racehorse:",
    ":french_bread:",
    ":duck:",
    "spt",
    "spt2",
    "***blacklist commodore***",
    "***women\nbe\nshopping***",
    "bukbot's funny body movement makes me have anything",
    ":thinking:",
    "i love building pyramids",
    "dævid bjøwie",
    "Davidt Gilmourt",
    "GILMOUR & PINK FLOYD",
    "THE WATERS FUNNY MOVEMENT MAKES ME HAVE ANYTHING",
    "YOU CHOICE",
    "THE WATERS",
    "SDFNJKSNJEQWERQKEQQ2LQNRL23OHR23HRNERADFSBBWDJLQBLQWDQDNWDFJEWPABDSKJBCF23HNQROU32U0JNLASBFLDBDLNBAJLSLFEQWR K23RBFDNASNJJSJDDFHDDISDFSDFI999999999999999999999999999999999",
    "ƒ˙˙ƒ∂ßƒ∑ø¥ƒ£¢º£•¥˙ˆß¬˜¬∂ßff",
    "PLELEDSE STOP",
    "ssssssssssssssssssssspppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppptttttttttttttttttttttttttt"
]

#jake
jake = [
    "Shut up you colonial your opinion is invalid",
    "hey we're mr worldwide",
    "yeah he's a pleb init",
    "@Lemon buscus wants to drink your juice",
    "bean picture",
    "bean picture",
    "bean picture",
    "bean picture",
    "Raquel is going to beat me up when she sees these pictures",
    "eat my perpletuous ass",
    "soggy scones",
    "dickhead",
    "uh",
    "wanker",
    "fuck up faggot",
    "fuck up cunt",
    "ryan is chav",
    "in your imagination",
    "australian law doesnt dictate me",
    "your running low on excuses",
    "sheiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiit",
    "it was me who started the dog fucking meme",
    "i love my doggo",
    "WAIT I HAVE A SHEP NOW",
    "me x doggo",
    "NONO but not a sexual relationship",
    "XD",
    "Robin has tiny nipples",
    "The pepsi army is silent but strong",
    "You will never be british",
    "Ahaha you fucking egg",
    "OK but real shit is ass a liquid or solid because it bounces around like jelly which means its liquid but your hand doesn't go though it so",
    "damn why is it so high",
    "So robin is high\nAnd a nonce",
    "y'all are eggs",
    "Im a selfish person and I always feel bad :shrug:",
    "well im not that selfish",
    "only on tuesdays",
    "im gonna die",
    ":>",
    "i like chik cen",
    "noe",
    "https://cdn.discordapp.com/attachments/394178583784062976/399622498188001289/9UApAaA.jpg",
    "rich tea biscuits",
    "I'd rather eat food and get fat then having a chance of stds :shrug:",
    "the queen is cool",
    "boi im gonna beat your ass how dare u disrepesct the queen",
    "britains cooler then australia though",
    "eat my ass",
    "eat my ass",
    "eat my ass",
    "eat my ass",
    "eat my ass",
    "you're an Egg",
    "Fuck",
    "If I'm destined to work at tesco my whole life I'm gonna eat M&Ms on the job",
    "water is wet",
    "pepsi over coke",
    "fuck coke",
    "i love pepsi",
    "i dont go to a private school and i'm not rich",
    "I can relate to everything the bot says about me\nprobably because I said it"
]
    

#kurt
zekurt = [
    "viva la poutine",
    "viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine viva la poutine",
    "you fucking wot mate",
    "*torenaments*",
    "i was told canada was cold",
    "viva la tim hortons",
    "https://cdn.discordapp.com/attachments/352132036552556554/398373970673532928/8V013MC.png",
    "fuck you guys and your snow day",
    "haha xd",
    "viva la milk bags",
    "fuckboi indeed",
    "damn",
    "ah shit",
    #these following 3 are together
    "hah get fucked my 2018 will last longer than yours",
    "\nalso I'd like to say that I fulfilled my wish"
    "\nto nut exactly at 12"
    "shit",
    "thought we killed galahad",
    "we fucked",
    "yeah i hate that guy",
    "yall are allowed into the club",
    "if Kash the Pure does then I'm sure everyone does",
    "lmao all good",
    "rip kash :broken_heart:",
    "fuck cumwhore",
    ":eyes: confirmed",
    "remember boys and girls god isn't real",
    "death is nothingness for eternity",
    "connor is a disappointment",
    "connor ***DROPS DICK ON TABLE*** I AM AN EXECUTIVE OBEY",
    "connor: hey guys just wanted to remind everyone that i am technically an executive",
    "everyone is death",
    "i am out i can't join",
    "Lil dick",
    "fuck you",
    "true",
    "https://i.redd.it/mf4rnsbonx501.jpg"
    "@ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut @ZeroEpoch1969#0051 nut",
    "i typed tree into cmd",
    "that's not gay because some of those men probably kissed women",
    "***can fat girls get away with murder if they accidentally crush their man while on top***  :thinking:",
    "P U P P E T  O W N E R",
    "cumwhore do you ever just open your mouth and then realize no one fucking cares",
    "MEGA BRITANNIA",
    "man i just fucking realized the Scandinavian flags are just crosses",
    "CASCADIA SHALL BE FREE",
    "VIVA LA CASCADIA",
    "get fucked",
    "discount austria",
    "not terrible",
    ";;;;;;;;;;;;;;;;;;;;;;;;;",
    "i can't believe the jar jar binks theory was true",
    ":eyes:",
    "***no nasty drama allowed on this christian server***",
    ":thinking:",
    "huh",
    "get reported",
    "god infamas pisses me off",
    "I'd probably get fucked",
    "i am so goddamn disappointed",
    "nut",
    "mecha trump",
    "that's my boy",
    "good job"
]